### Introduction to Tensorflow

In [1]:
import tensorflow as tf


In [104]:
import numpy as np

In [2]:
tf.__version__



'2.9.1'

In [4]:
# Create Tensors 

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Checking dimensions of scalar
scalar.ndim

0

In [6]:
# Creating a vector

vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [7]:
# Checking dimensions of vector

vector.ndim

1

In [8]:
#Creating a matrix

matrix = tf.constant([[10,7]
,[7,10]])

In [9]:
matrix.ndim

2

In [12]:
another_matrix = tf.constant([[10.,7.],
[7.,10.],
[2.,9.]],dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 2.,  9.]], dtype=float16)>

In [13]:
#Creating a tensor

tensor = tf.constant([[[1,2,3],
                        [4,5,6]],
                        
                        
                        [[7,8,9],
                        [10,11,12]],
                        
                        [[13,14,15],
                        [16,17,18]]])


tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [14]:
tensor.ndim

3

In [25]:
# Creating a random tensor

tf.random.set_seed(42)

tf.random.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519],
       [-2.3880599, -1.0392479]], dtype=float32)>

In [26]:
# Shuffling the order of tensors

not_shuffled = tf.constant([[10,7],
                             [3,4],
                             [2,5]])


not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [53]:

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### Getting information from tensors

In [55]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [56]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [63]:
print("Datatype of every element : ",rank_4_tensor.dtype)
print("Number of dimensions : ",rank_4_tensor.ndim)
print("Shape of tensors : ",rank_4_tensor.shape)
print("Elements along the 0 axis : ",rank_4_tensor.shape[0])
print("Elements along the last axis : ",rank_4_tensor.shape[-1])
print("Total No. of elements in our tensor : ",tf.size(rank_4_tensor).numpy())

Datatype of every element :  <dtype: 'float32'>
Number of dimensions :  4
Shape of tensors :  (2, 3, 4, 5)
Elements along the 0 axis :  2
Elements along the last axis :  5
Total No. of elements in our tensor :  120


### Indexing tensors

In [75]:
# Finding the first 2 elements of every dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [79]:
#Get first elements from each dimension except for the final one


rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [80]:
rank2_tensor = tf.constant([[10,7],
                            [2,9]])

rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  9]])>

In [81]:
# get the last element of each dimension of rank 2 tensor

rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9])>

In [82]:
# Add an extra dimension to our rank 2 tensor

rank3  = rank2_tensor[...,tf.newaxis]
rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 9]]])>

In [84]:
# Alternative to newaxis

tf.expand_dims(rank2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 9]]])>

### Manipulating tensors with basic operations

In [85]:
tensor = tf.constant([[10,7],[2,9]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  9]])>

In [87]:
tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 19]])>

In [88]:
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  90]])>

In [89]:
tf.math.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-8, -1]])>

In [90]:
tf.math.divide(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.2, 0.9]])>

### Matrix multiplication using tensors

When multiplying 2 tensors, if one of the axis from a tensor does not line up, you can either reshape or transpose a matrix. (transpose is preferred)

In [100]:
tensor1 = tf.constant([[10,7],[2,9]])
tensor2 = tf.constant([[11,8],[3,10]])


In [101]:
tf.linalg.matmul(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[131, 150],
       [ 49, 106]])>

In [102]:
tensor1 @ tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[131, 150],
       [ 49, 106]])>

### Aggregating tensors 

In [106]:
x = tf.constant(np.random.randint(1,100,size=50))
x

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 9, 53, 40,  4, 25, 91, 82, 55, 51, 39, 69, 81, 39, 34, 71, 31, 41,
       57, 70, 46, 85, 81, 94, 30, 29, 50, 13, 28, 98, 98, 44, 82, 69, 61,
       88, 75, 17, 56, 81, 79, 90, 36, 81, 78, 91, 56, 98, 29, 69, 16])>

In [107]:
# Absolute of a tensor

tf.abs(x)

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 9, 53, 40,  4, 25, 91, 82, 55, 51, 39, 69, 81, 39, 34, 71, 31, 41,
       57, 70, 46, 85, 81, 94, 30, 29, 50, 13, 28, 98, 98, 44, 82, 69, 61,
       88, 75, 17, 56, 81, 79, 90, 36, 81, 78, 91, 56, 98, 29, 69, 16])>

In [112]:
# Minimum  in a tensor
tf.reduce_min(x)



<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [113]:
# Maximum in a tensor
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [115]:
# Mean value of tensor

tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int32, numpy=57>

In [116]:
# Sum of a tensor

tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2890>

In [123]:
# Variance 

tf.math.reduce_variance(tf.cast(x,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=697.5>

In [124]:
# Standard deviation

tf.math.reduce_std(tf.cast(x,dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=26.4>

In [128]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=(50,))

F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [129]:
tf.math.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [130]:
F[tf.math.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [131]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [132]:
F[tf.math.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing tensors

In [133]:
tf.random.set_seed(42)
x = tf.random.uniform(shape = (1,1,1,50))
x

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [134]:
x_squeezed  = tf.squeeze(x)
x_squeezed,x_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One Hot Encoding

In [135]:
some_list = [0,1,2,3]

tf.one_hot(some_list,depth =4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>