### Introduction to Tensorflow

In [1]:
import tensorflow as tf


In [2]:
tf.__version__



'2.9.1'

In [4]:
# Create Tensors 

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Checking dimensions of scalar
scalar.ndim

0

In [6]:
# Creating a vector

vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [7]:
# Checking dimensions of vector

vector.ndim

1

In [8]:
#Creating a matrix

matrix = tf.constant([[10,7]
,[7,10]])

In [9]:
matrix.ndim

2

In [12]:
another_matrix = tf.constant([[10.,7.],
[7.,10.],
[2.,9.]],dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 2.,  9.]], dtype=float16)>

In [13]:
#Creating a tensor

tensor = tf.constant([[[1,2,3],
                        [4,5,6]],
                        
                        
                        [[7,8,9],
                        [10,11,12]],
                        
                        [[13,14,15],
                        [16,17,18]]])


tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [14]:
tensor.ndim

3

In [25]:
# Creating a random tensor

tf.random.set_seed(42)

tf.random.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519],
       [-2.3880599, -1.0392479]], dtype=float32)>

In [26]:
# Shuffling the order of tensors

not_shuffled = tf.constant([[10,7],
                             [3,4],
                             [2,5]])


not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [53]:

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### Getting information from tensors

In [55]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [56]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [63]:
print("Datatype of every element : ",rank_4_tensor.dtype)
print("Number of dimensions : ",rank_4_tensor.ndim)
print("Shape of tensors : ",rank_4_tensor.shape)
print("Elements along the 0 axis : ",rank_4_tensor.shape[0])
print("Elements along the last axis : ",rank_4_tensor.shape[-1])
print("Total No. of elements in our tensor : ",tf.size(rank_4_tensor).numpy())

Datatype of every element :  <dtype: 'float32'>
Number of dimensions :  4
Shape of tensors :  (2, 3, 4, 5)
Elements along the 0 axis :  2
Elements along the last axis :  5
Total No. of elements in our tensor :  120


### Indexing tensors

In [75]:
# Finding the first 2 elements of every dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [79]:
#Get first elements from each dimension except for the final one


rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [80]:
rank2_tensor = tf.constant([[10,7],
                            [2,9]])

rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  9]])>

In [81]:
# get the last element of each dimension of rank 2 tensor

rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9])>

In [82]:
# Add an extra dimension to our rank 2 tensor

rank3  = rank2_tensor[...,tf.newaxis]
rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 9]]])>

In [84]:
# Alternative to newaxis

tf.expand_dims(rank2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 9]]])>